import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faShareNodes,
  faHouse,
  faHeart,
  faBraille,
  faNewspaper,
  faArrowDownAZ,
  faMoon,
  faSun,
  faCrown,
  faMagnifyingGlass,
  faFire,
  faCheck,
  faDog,
  faGamepad,
  faShirt,
  faSpa,
  faCar,
  faStore,
  faPlaneArrival,
  faClockRotateLeft,
  faMobileScreenButton,
  faBriefcase,
  faDrumstickBite,
  faFutbol,
  faBaby,
  faComputer,
  faChair,
  faSackDollar,
  faGifts,
  faBook,
  faSmileBeam,
  faBars,
  faChevronUp,
  faEye,
  faStar,
  faEllipsisH,
  faShareAlt,
  faCircleChevronDown,
  faUpRightFromSquare,
  faCircleInfo,
  faShare,
  faXmark,
  faClone } from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false

library.add(
  faHouse,
  faHeart,
  faBraille,
  faNewspaper,
  faArrowDownAZ,
  faMoon,
  faSun,
  faCrown,
  faMagnifyingGlass,
  faFire,
  faCheck,
  faDog,
  faGamepad,
  faShirt,
  faSpa,
  faCar,
  faStore,
  faPlaneArrival,
  faClockRotateLeft,
  faMobileScreenButton,
  faBriefcase,
  faDrumstickBite,
  faFutbol,
  faBaby,
  faComputer,
  faChair,
  faSackDollar,
  faGifts,
  faBook,
  faSmileBeam,
  faBars,
  faChevronUp,
  faEye,
  faStar,
  faEllipsisH,
  faShareAlt,
  faCircleChevronDown,
  faUpRightFromSquare,
  faCircleInfo,
  faShare,
  faXmark,
  faClone
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('fa', FontAwesomeIcon, {})
})

